steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - router_backend/Dockerfile
      - -t
      - asia-east1-docker.pkg.dev/gen-lang-client-0302375476/cloud-run-source-deploy/ntpu-router:latest
      - router_backend
images:
  - asia-east1-docker.pkg.dev/gen-lang-client-0302375476/cloud-run-source-deploy/ntpu-router:latest
